# Generated by Django 3.0.8 on 2020-07-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
